project_id = "yxpnkipcoxksmnsvpvwi"

[functions.merchant-dashboard]
verify_jwt = true

[functions.merchant-transactions]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-connect-account]
verify_jwt = true

[functions.create-subscription-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.get-wallet]
verify_jwt = true

[functions.redeem-wallet]
verify_jwt = true

[functions.get-wallet-history]
verify_jwt = true

[functions.admin-update-merchant]
verify_jwt = true

[functions.admin-update-funding-request]
verify_jwt = true

[functions.admin-issue-refund]
verify_jwt = true

[functions.admin-update-user-role]
verify_jwt = true
