// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-merchants.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^3.23.8";
function supabaseFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_merchants_default = defineTool({
  name: "search_merchants",
  title: "Search PawBucks merchants",
  description: "Search public PawBucks merchants by business name or category. Returns up to 20 matches.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Search text matched against business name or category."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseFor(ctx);
    const { data, error } = await sb.from("merchants_public").select("id, business_name, business_type, city, state").or(`business_name.ilike.%${query}%,business_type.ilike.%${query}%`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-pawbucks-balance.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
function supabaseFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_pawbucks_balance_default = defineTool2({
  name: "my_pawbucks_balance",
  title: "Get my PawBucks balance",
  description: "Return the signed-in user's PawBucks wallet balance and USD equivalent.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseFor2(ctx);
    const { data, error } = await sb.from("wallets").select("balance").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const balance = Number(data?.balance ?? 0);
    const usd = (balance / 1e3).toFixed(2);
    return {
      content: [{ type: "text", text: `Balance: ${balance} PawBucks ($${usd} USD)` }],
      structuredContent: { pawbucks: balance, usd: Number(usd) }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yxpnkipcoxksmnsvpvwi";
var mcp_default = defineMcp({
  name: "pawbucks-mcp",
  title: "PawBucks",
  version: "0.1.0",
  instructions: "Tools for the PawBucks pet rewards platform. Use `search_merchants` to find local pet businesses, and `my_pawbucks_balance` to read the signed-in user's wallet balance in PawBucks and USD.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_merchants_default, my_pawbucks_balance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
